version: "3"
networks:
  internal: # ðŸ‘ˆ DEFINE the network
    driver: bridge
services:
  nginx:
    image: nginx:latest
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/omkarshinde/nginx-cert:/etc/nginx/certs:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - internal

  app1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - APP_NAME=app1
    networks:
      - internal

  app2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - APP_NAME=app2
    networks:
      - internal

  app3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - APP_NAME=app3
    networks:
      - internal
